# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_messages_stop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='stop_id',
            field=models.CharField(max_length=200),
        ),
    ]
